INFO  - 2018-02-08 14:52:50,693 
"GET /polls/1/ HTTP/1.1" 200 466 
--------------------------------------------------------------------------------
ERROR - 2018-02-08 14:53:05,244 
Internal Server Error: /polls/1/vote/ 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\github\django_template\venv\lib\site-packages\django\utils\datastructures.py", line 77, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'choice'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\github\django_template\project\apps\polls\views.py", line 52, in vote
    selected_choice = question.choice_set.get(pk=request.POST['choice'])
  File "E:\github\django_template\venv\lib\site-packages\django\utils\datastructures.py", line 79, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'choice'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\github\django_template\project\libs\decorator.py", line 15, in _deco
    return func(request, *args, **kwargs)
  File "E:\github\django_template\project\apps\polls\views.py", line 56, in vote
    return rendr(request, 'polls/detail.html', {
NameError: name 'rendr' is not defined
ERROR - 2018-02-08 14:53:05,309 
"POST /polls/1/vote/ HTTP/1.1" 500 83836 
--------------------------------------------------------------------------------
INFO  - 2018-02-08 14:53:30,125 - basehttp.py - log_message -  
"GET /polls/1/ HTTP/1.1" 200 466 
--------------------------------------------------------------------------------
ERROR - 2018-02-08 14:53:47,767 - exception.py - handle_uncaught_exception   
Internal Server Error: /polls/1/vote/ 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\github\django_template\venv\lib\site-packages\django\utils\datastructures.py", line 77, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'choice'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\github\django_template\project\apps\polls\views.py", line 52, in vote
    selected_choice = question.choice_set.get(pk=request.POST['choice'])
  File "E:\github\django_template\venv\lib\site-packages\django\utils\datastructures.py", line 79, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'choice'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\github\django_template\project\libs\decorator.py", line 15, in _deco
    return func(request, *args, **kwargs)
  File "E:\github\django_template\project\apps\polls\views.py", line 56, in vote
    return rendr(request, 'polls/detail.html', {
NameError: name 'rendr' is not defined
ERROR - 2018-02-08 14:53:47,827 - basehttp.py - log_message   
"POST /polls/1/vote/ HTTP/1.1" 500 83837 
--------------------------------------------------------------------------------
INFO  - 2018-02-08 14:54:16,099 - basehttp.py  - log_message   
"GET /polls/1/ HTTP/1.1" 200 466 
--------------------------------------------------------------------------------
INFO  - 2018-02-08 14:54:26,342 - basehttp.py  - log_message   
"GET /polls/1/ HTTP/1.1" 200 466 
--------------------------------------------------------------------------------
¡¾INFO  ¡¿- 2018-02-08 14:55:44,671 - basehttp.py  - log_message   
"GET /polls/1/ HTTP/1.1" 200 466 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-08 14:56:22,008 - basehttp.py  - log_message   
"GET /polls/1/ HTTP/1.1" 200 466 
--------------------------------------------------------------------------------
[ERROR ]- 2018-02-08 14:56:26,729 - exception.py - handle_uncaught_exception   
Internal Server Error: /polls/1/vote/ 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\github\django_template\venv\lib\site-packages\django\utils\datastructures.py", line 77, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'choice'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\github\django_template\project\apps\polls\views.py", line 52, in vote
    selected_choice = question.choice_set.get(pk=request.POST['choice'])
  File "E:\github\django_template\venv\lib\site-packages\django\utils\datastructures.py", line 79, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'choice'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\github\django_template\project\libs\decorator.py", line 15, in _deco
    return func(request, *args, **kwargs)
  File "E:\github\django_template\project\apps\polls\views.py", line 56, in vote
    return rendr(request, 'polls/detail.html', {
NameError: name 'rendr' is not defined
[ERROR ]- 2018-02-08 14:56:26,832 - basehttp.py  - log_message   
"POST /polls/1/vote/ HTTP/1.1" 500 83841 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-08 16:34:40,874 - basehttp.py  - log_message   
"GET /polls/1/ HTTP/1.1" 200 466 
--------------------------------------------------------------------------------
[WARNING]- 2018-02-08 16:34:40,994 - base.py      - get_response   
Not Found: /favicon.ico 
--------------------------------------------------------------------------------
[WARNING]- 2018-02-08 16:34:40,996 - basehttp.py  - log_message   
"GET /favicon.ico HTTP/1.1" 404 2179 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:32:05,462 - basehttp.py  - log_message   
"GET / HTTP/1.1" 200 135 
--------------------------------------------------------------------------------
[WARNING]- 2018-02-09 14:32:05,893 - base.py      - get_response   
Not Found: /favicon.ico 
--------------------------------------------------------------------------------
[WARNING]- 2018-02-09 14:32:05,894 - basehttp.py  - log_message   
"GET /favicon.ico HTTP/1.1" 404 2179 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:53:24,677 - basehttp.py  - log_message   
"GET /admin/ HTTP/1.1" 302 0 
--------------------------------------------------------------------------------
[ERROR ]- 2018-02-09 14:53:24,752 - exception.py - handle_uncaught_exception   
Internal Server Error: /admin/login/ 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\base.py", line 156, in _get_response
    response = response.render()
  File "E:\github\django_template\venv\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "E:\github\django_template\venv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "E:\github\django_template\venv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "E:\github\django_template\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: admin/login.html
[ERROR ]- 2018-02-09 14:53:24,824 - basehttp.py  - log_message   
"GET /admin/login/?next=/admin/ HTTP/1.1" 500 81837 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:14,963 - basehttp.py  - log_message   
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 1855 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:14,982 - basehttp.py  - log_message   
"GET /static/admin/css/login.css HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:14,986 - basehttp.py  - log_message   
"GET /static/admin/css/base.css HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:14,989 - basehttp.py  - log_message   
"GET /static/admin/css/responsive.css HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:15,019 - basehttp.py  - log_message   
"GET /static/admin/css/fonts.css HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:15,025 - basehttp.py  - log_message   
"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:15,044 - basehttp.py  - log_message   
"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:20,006 - basehttp.py  - log_message   
"GET /polls/ HTTP/1.1" 200 368 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:20,029 - basehttp.py  - log_message   
"GET /static/polls/style.css HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:22,897 - basehttp.py  - log_message   
"GET /polls/1/ HTTP/1.1" 200 466 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:30,012 - basehttp.py  - log_message   
"GET /admin/ HTTP/1.1" 302 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:30,034 - basehttp.py  - log_message   
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 1855 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:33,652 - basehttp.py  - log_message   
"GET /admin/ HTTP/1.1" 302 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:33,679 - basehttp.py  - log_message   
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 1855 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:43,188 - basehttp.py  - log_message   
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:43,256 - basehttp.py  - log_message   
"GET /admin/ HTTP/1.1" 200 4653 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:43,274 - basehttp.py  - log_message   
"GET /static/admin/css/dashboard.css HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:43,299 - basehttp.py  - log_message   
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:43,300 - basehttp.py  - log_message   
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:43,301 - basehttp.py  - log_message   
"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:55,398 - basehttp.py  - log_message   
"GET /admin/auth/group/ HTTP/1.1" 200 3587 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:55,434 - basehttp.py  - log_message   
"GET /static/admin/css/changelists.css HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:55,436 - basehttp.py  - log_message   
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:55,438 - basehttp.py  - log_message   
"GET /static/admin/js/core.js HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:55,442 - basehttp.py  - log_message   
"GET /admin/jsi18n/ HTTP/1.1" 200 3185 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:55,462 - basehttp.py  - log_message   
"GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:55,449 - basehttp.py  - log_message   
"GET /static/admin/js/urlify.js HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:55,450 - basehttp.py  - log_message   
"GET /static/admin/js/jquery.init.js HTTP/1.1" 200 363 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:55,448 - basehttp.py  - log_message   
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:55,476 - basehttp.py  - log_message   
"GET /static/admin/js/actions.js HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:55,480 - basehttp.py  - log_message   
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:55,529 - basehttp.py  - log_message   
"GET /static/admin/img/search.svg HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:55,615 - basehttp.py  - log_message   
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:56:58,771 - basehttp.py  - log_message   
"GET /admin/ HTTP/1.1" 200 4653 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:57:00,148 - basehttp.py  - log_message   
"GET /admin/auth/user/ HTTP/1.1" 200 6679 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:57:00,164 - basehttp.py  - log_message   
"GET /admin/jsi18n/ HTTP/1.1" 200 3185 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:57:00,168 - basehttp.py  - log_message   
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:57:00,234 - basehttp.py  - log_message   
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:57:03,998 - basehttp.py  - log_message   
"GET /admin/ HTTP/1.1" 200 4653 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:57:08,022 - basehttp.py  - log_message   
"GET /admin/auth/user/ HTTP/1.1" 200 6679 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:57:08,039 - basehttp.py  - log_message   
"GET /admin/jsi18n/ HTTP/1.1" 200 3185 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:57:21,611 - basehttp.py  - log_message   
"GET /admin/ HTTP/1.1" 200 4653 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:57:23,221 - basehttp.py  - log_message   
"GET /admin/auth/user/ HTTP/1.1" 200 6679 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:57:23,238 - basehttp.py  - log_message   
"GET /admin/jsi18n/ HTTP/1.1" 200 3185 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:57:24,394 - basehttp.py  - log_message   
"GET /admin/auth/user/add/ HTTP/1.1" 200 5709 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:57:24,420 - basehttp.py  - log_message   
"GET /static/admin/css/forms.css HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:57:24,435 - basehttp.py  - log_message   
"GET /static/admin/js/change_form.js HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:57:24,437 - basehttp.py  - log_message   
"GET /admin/jsi18n/ HTTP/1.1" 200 3185 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:57:24,442 - basehttp.py  - log_message   
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:57:24,442 - basehttp.py  - log_message   
"GET /static/admin/css/widgets.css HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:57:31,652 - basehttp.py  - log_message   
"GET /admin/auth/user/ HTTP/1.1" 200 6679 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:57:35,661 - basehttp.py  - log_message   
"GET / HTTP/1.1" 200 135 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 14:57:37,334 - basehttp.py  - log_message   
"GET /admin/auth/user/ HTTP/1.1" 200 6679 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 17:04:10,092 - basehttp.py  - log_message   
"GET /admin/ HTTP/1.1" 200 4653 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:02:54,171 - basehttp.py  - log_message   
"GET / HTTP/1.1" 200 135 
--------------------------------------------------------------------------------
[WARNING]- 2018-02-09 18:03:02,262 - base.py      - get_response   
Not Found: /auth/register 
--------------------------------------------------------------------------------
[WARNING]- 2018-02-09 18:03:02,264 - basehttp.py  - log_message   
"GET /auth/register HTTP/1.1" 404 2524 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:03:08,121 - basehttp.py  - log_message   
"GET /auth/reg HTTP/1.1" 301 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:03:08,129 - basehttp.py  - log_message   
"GET /auth/reg/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:04:13,768 - basehttp.py  - log_message   
"GET /auth/reg/ HTTP/1.1" 200 373 
--------------------------------------------------------------------------------
[WARNING]- 2018-02-09 18:04:29,487 - base.py      - get_response   
Not Found: /register 
--------------------------------------------------------------------------------
[WARNING]- 2018-02-09 18:04:29,491 - basehttp.py  - log_message   
"POST /register HTTP/1.1" 404 2276 
--------------------------------------------------------------------------------
[WARNING]- 2018-02-09 18:05:57,343 - base.py      - get_response   
Not Found: /register 
--------------------------------------------------------------------------------
[WARNING]- 2018-02-09 18:05:57,345 - basehttp.py  - log_message   
"POST /register HTTP/1.1" 404 2276 
--------------------------------------------------------------------------------
[WARNING]- 2018-02-09 18:06:57,898 - base.py      - get_response   
Not Found: /register 
--------------------------------------------------------------------------------
[WARNING]- 2018-02-09 18:06:57,903 - basehttp.py  - log_message   
"POST /register HTTP/1.1" 404 2276 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:07:02,290 - basehttp.py  - log_message   
"GET /auth/reg/ HTTP/1.1" 200 377 
--------------------------------------------------------------------------------
[WARNING]- 2018-02-09 18:07:09,948 - base.py      - get_response   
Not Found: /log/register 
--------------------------------------------------------------------------------
[WARNING]- 2018-02-09 18:07:09,953 - basehttp.py  - log_message   
"POST /log/register HTTP/1.1" 404 2288 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:07:33,095 - basehttp.py  - log_message   
"GET /auth/reg/ HTTP/1.1" 200 378 
--------------------------------------------------------------------------------
[ERROR ]- 2018-02-09 18:07:39,590 - exception.py - handle_uncaught_exception   
Internal Server Error: /auth/register 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\github\django_template\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "E:\github\django_template\venv\lib\site-packages\django\middleware\common.py", line 61, in process_request
    path = self.get_full_path_with_slash(request)
  File "E:\github\django_template\venv\lib\site-packages\django\middleware\common.py", line 99, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/auth/register/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
[ERROR ]- 2018-02-09 18:07:39,735 - basehttp.py  - log_message   
"POST /auth/register HTTP/1.1" 500 68536 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:08:16,948 - basehttp.py  - log_message   
"GET /auth/reg/ HTTP/1.1" 200 379 
--------------------------------------------------------------------------------
[ERROR ]- 2018-02-09 18:08:24,265 - exception.py - handle_uncaught_exception   
Internal Server Error: /auth/register/ 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\github\django_template\project\common\decorator.py", line 19, in _deco
    return func(request, *args, **kwargs)
  File "E:\github\django_template\project\apps\log\views.py", line 37, in register
    User.save()
TypeError: save() missing 1 required positional argument: 'self'
[ERROR ]- 2018-02-09 18:08:24,304 - basehttp.py  - log_message   
"POST /auth/register/ HTTP/1.1" 500 73705 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:11:48,988 - basehttp.py  - log_message   
"GET /auth/reg/ HTTP/1.1" 200 379 
--------------------------------------------------------------------------------
[ERROR ]- 2018-02-09 18:12:00,496 - exception.py - handle_uncaught_exception   
Internal Server Error: /auth/register/ 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\github\django_template\project\common\decorator.py", line 19, in _deco
    return func(request, *args, **kwargs)
  File "E:\github\django_template\project\apps\log\views.py", line 37, in register
    User.save()
TypeError: save() missing 1 required positional argument: 'self'
[ERROR ]- 2018-02-09 18:12:00,564 - basehttp.py  - log_message   
"POST /auth/register/ HTTP/1.1" 500 73694 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:12:18,647 - basehttp.py  - log_message   
"POST /auth/register/ HTTP/1.1" 200 17 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:12:37,008 - basehttp.py  - log_message   
"POST /auth/register/ HTTP/1.1" 200 17 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:13:01,732 - basehttp.py  - log_message   
"POST /auth/register/ HTTP/1.1" 200 17 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:13:09,268 - basehttp.py  - log_message   
"POST /auth/register/ HTTP/1.1" 200 17 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:14:31,096 - basehttp.py  - log_message   
"POST /auth/register/ HTTP/1.1" 200 17 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:14:40,170 - basehttp.py  - log_message   
"GET /admin/ HTTP/1.1" 200 4653 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:14:51,275 - basehttp.py  - log_message   
"GET /admin/ HTTP/1.1" 200 5264 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:14:53,481 - basehttp.py  - log_message   
"GET /admin/log/user/ HTTP/1.1" 200 5437 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:14:53,507 - basehttp.py  - log_message   
"GET /admin/jsi18n/ HTTP/1.1" 200 3185 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:14:57,800 - basehttp.py  - log_message   
"GET /admin/log/user/6/change/ HTTP/1.1" 200 5273 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:14:57,820 - basehttp.py  - log_message   
"GET /admin/jsi18n/ HTTP/1.1" 200 3185 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:16:55,330 - basehttp.py  - log_message   
"GET /admin/log/user/ HTTP/1.1" 200 5437 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:16:55,346 - basehttp.py  - log_message   
"GET /admin/jsi18n/ HTTP/1.1" 200 3185 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:19:38,360 - basehttp.py  - log_message   
"GET /auth/reg/ HTTP/1.1" 200 379 
--------------------------------------------------------------------------------
[WARNING]- 2018-02-09 18:19:44,357 - base.py      - get_response   
Not Found: /auth/log 
--------------------------------------------------------------------------------
[WARNING]- 2018-02-09 18:19:44,359 - basehttp.py  - log_message   
"GET /auth/log HTTP/1.1" 404 2682 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:20:40,827 - basehttp.py  - log_message   
"GET /auth/reg/ HTTP/1.1" 200 379 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:20:46,281 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 379 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:24:48,794 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 379 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:25:13,077 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 379 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:25:20,532 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[ERROR ]- 2018-02-09 18:25:29,243 - exception.py - handle_uncaught_exception   
Internal Server Error: /auth/login/ 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\github\django_template\project\common\decorator.py", line 19, in _deco
    return func(request, *args, **kwargs)
  File "E:\github\django_template\project\apps\log\views.py", line 42, in login
    return render_to_response('login.html',{'userform':userform})
NameError: name 'render_to_response' is not defined
[ERROR ]- 2018-02-09 18:25:29,310 - basehttp.py  - log_message   
"POST /auth/login/ HTTP/1.1" 500 72921 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:27:03,381 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:27:06,310 - basehttp.py  - log_message   
"POST /auth/login/ HTTP/1.1" 200 10 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:28:42,368 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:28:44,400 - basehttp.py  - log_message   
"POST /auth/login/ HTTP/1.1" 200 10 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:28:51,974 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:28:52,806 - basehttp.py  - log_message   
"POST /auth/login/ HTTP/1.1" 200 220 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:30:37,905 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-09 18:30:45,051 - basehttp.py  - log_message   
"POST /auth/login/ HTTP/1.1" 200 220 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 09:28:18,255 - basehttp.py  - log_message   
"GET / HTTP/1.1" 200 136 
--------------------------------------------------------------------------------
[WARNING]- 2018-02-22 09:37:39,056 - base.py      - get_response   
Not Found: /register 
--------------------------------------------------------------------------------
[WARNING]- 2018-02-22 09:37:39,060 - basehttp.py  - log_message   
"GET /register HTTP/1.1" 404 2275 
--------------------------------------------------------------------------------
[WARNING]- 2018-02-22 09:37:43,711 - base.py      - get_response   
Not Found: /log/register 
--------------------------------------------------------------------------------
[WARNING]- 2018-02-22 09:37:43,713 - basehttp.py  - log_message   
"GET /log/register HTTP/1.1" 404 2287 
--------------------------------------------------------------------------------
[WARNING]- 2018-02-22 09:37:47,945 - base.py      - get_response   
Not Found: /log/register/ 
--------------------------------------------------------------------------------
[WARNING]- 2018-02-22 09:37:47,947 - basehttp.py  - log_message   
"GET /log/register/ HTTP/1.1" 404 2290 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 09:38:29,651 - basehttp.py  - log_message   
"GET /auth/register/ HTTP/1.1" 200 62 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 09:38:38,231 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 09:38:41,305 - basehttp.py  - log_message   
"POST /auth/login/ HTTP/1.1" 200 220 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 11:16:40,336 - basehttp.py  - log_message   
"POST /auth/login/ HTTP/1.1" 200 220 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 11:17:48,313 - basehttp.py  - log_message   
"POST /auth/login/ HTTP/1.1" 200 220 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 11:18:49,031 - basehttp.py  - log_message   
"POST /auth/login/ HTTP/1.1" 200 220 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 11:18:55,729 - basehttp.py  - log_message   
"POST /auth/login/ HTTP/1.1" 200 218 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 11:21:21,995 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 11:21:29,672 - basehttp.py  - log_message   
"POST /auth/login/ HTTP/1.1" 200 618 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:04:04,170 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:04:07,022 - basehttp.py  - log_message   
"POST /auth/login/ HTTP/1.1" 200 220 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:04:37,805 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:04:39,552 - basehttp.py  - log_message   
"POST /auth/login/ HTTP/1.1" 200 220 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:06:08,576 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:06:17,048 - basehttp.py  - log_message   
"POST /auth/login/ HTTP/1.1" 200 220 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:06:46,412 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:06:49,613 - basehttp.py  - log_message   
"POST /auth/login/ HTTP/1.1" 200 220 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:07:48,085 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:07:49,065 - basehttp.py  - log_message   
"POST /auth/login/ HTTP/1.1" 200 220 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:10:45,834 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:10:48,074 - basehttp.py  - log_message   
"POST /auth/login/ HTTP/1.1" 200 220 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:11:43,294 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:11:44,911 - basehttp.py  - log_message   
"POST /auth/login/ HTTP/1.1" 200 220 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:12:33,728 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:12:35,104 - basehttp.py  - log_message   
"POST /auth/login/ HTTP/1.1" 200 220 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:14:00,593 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:14:01,429 - basehttp.py  - log_message   
"POST /auth/login/ HTTP/1.1" 200 220 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:16:09,473 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:16:10,997 - basehttp.py  - log_message   
"POST /auth/login/ HTTP/1.1" 200 220 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:17:32,333 - basehttp.py  - log_message   
"POST /auth/login/ HTTP/1.1" 200 220 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:20:50,115 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:21:23,331 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:21:24,251 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:21:25,432 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:21:45,232 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:21:45,872 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:21:47,231 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:22:02,090 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:22:02,769 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:22:03,346 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:24:08,507 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:30:05,530 - basehttp.py  - log_message   
"GET /auth/login/ HTTP/1.1" 200 59 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:30:27,920 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[ERROR ]- 2018-02-22 14:30:51,209 - exception.py - handle_uncaught_exception   
Internal Server Error: /auth/login/ 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:/github/django_template\project\common\decorator.py", line 19, in _deco
    return func(request, *args, **kwargs)
  File "E:/github/django_template\project\apps\log\views.py", line 32, in login
    username = userform.cleaned_data['username']
AttributeError: 'UserForm' object has no attribute 'cleaned_data'
[INFO  ]- 2018-02-22 14:31:28,560 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:31:29,466 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[ERROR ]- 2018-02-22 14:31:30,810 - exception.py - handle_uncaught_exception   
Internal Server Error: /auth/login/ 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:/github/django_template\project\common\decorator.py", line 19, in _deco
    return func(request, *args, **kwargs)
  File "E:/github/django_template\project\apps\log\views.py", line 32, in login
    username = userform.cleaned_data['username']
AttributeError: 'UserForm' object has no attribute 'cleaned_data'
[ERROR ]- 2018-02-22 14:31:30,937 - basehttp.py  - log_message   
"POST /auth/login/ HTTP/1.1" 500 76284 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:32:25,403 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:35:05,596 - basehttp.py  - log_message   
"POST /auth/login/ HTTP/1.1" 200 618 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:35:47,045 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:35:56,648 - basehttp.py  - log_message   
"POST /auth/login/ HTTP/1.1" 200 273 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:36:41,710 - basehttp.py  - log_message   
"GET /auth/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[ERROR ]- 2018-02-22 14:36:46,776 - exception.py - handle_uncaught_exception   
Internal Server Error: /auth/login/ 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:/github/django_template\project\common\decorator.py", line 19, in _deco
    return func(request, *args, **kwargs)
  File "E:/github/django_template\project\apps\log\views.py", line 38, in login
    return render(request, 'index.html',{'userform':user.username})
AttributeError: 'QuerySet' object has no attribute 'username'
[ERROR ]- 2018-02-22 14:36:46,917 - basehttp.py  - log_message   
"POST /auth/login/ HTTP/1.1" 500 76945 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:42:59,914 - basehttp.py  - log_message   
"GET /polls/ HTTP/1.1" 200 368 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:42:59,938 - basehttp.py  - log_message   
"GET /static/polls/style.css HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:10,897 - basehttp.py  - log_message   
"GET /admin/ HTTP/1.1" 200 5264 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:10,914 - basehttp.py  - log_message   
"GET /static/admin/css/dashboard.css HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:10,915 - basehttp.py  - log_message   
"GET /static/admin/css/responsive.css HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:10,916 - basehttp.py  - log_message   
"GET /static/admin/css/base.css HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:10,934 - basehttp.py  - log_message   
"GET /static/admin/css/fonts.css HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:10,950 - basehttp.py  - log_message   
"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:10,950 - basehttp.py  - log_message   
"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:10,956 - basehttp.py  - log_message   
"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:10,958 - basehttp.py  - log_message   
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:10,959 - basehttp.py  - log_message   
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:13,700 - basehttp.py  - log_message   
"GET /admin/log/user/ HTTP/1.1" 200 5437 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:13,716 - basehttp.py  - log_message   
"GET /static/admin/css/changelists.css HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:13,731 - basehttp.py  - log_message   
"GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:13,734 - basehttp.py  - log_message   
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:13,747 - basehttp.py  - log_message   
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:13,751 - basehttp.py  - log_message   
"GET /static/admin/js/urlify.js HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:13,751 - basehttp.py  - log_message   
"GET /static/admin/js/core.js HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:13,754 - basehttp.py  - log_message   
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:13,756 - basehttp.py  - log_message   
"GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:13,764 - basehttp.py  - log_message   
"GET /admin/jsi18n/ HTTP/1.1" 200 3185 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:13,765 - basehttp.py  - log_message   
"GET /static/admin/js/actions.js HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:13,868 - basehttp.py  - log_message   
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:22,877 - basehttp.py  - log_message   
"GET /admin/log/user/6/change/ HTTP/1.1" 200 5273 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:22,895 - basehttp.py  - log_message   
"GET /static/admin/css/forms.css HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:22,902 - basehttp.py  - log_message   
"GET /admin/jsi18n/ HTTP/1.1" 200 3185 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:22,911 - basehttp.py  - log_message   
"GET /static/admin/js/change_form.js HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:22,915 - basehttp.py  - log_message   
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:22,917 - basehttp.py  - log_message   
"GET /static/admin/css/widgets.css HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:26,752 - basehttp.py  - log_message   
"GET /admin/log/user/ HTTP/1.1" 200 5437 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:42,223 - basehttp.py  - log_message   
"POST /admin/log/user/ HTTP/1.1" 200 3853 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:42,241 - basehttp.py  - log_message   
"GET /static/admin/js/cancel.js HTTP/1.1" 200 204 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:45,458 - basehttp.py  - log_message   
"POST /admin/log/user/ HTTP/1.1" 302 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:45,543 - basehttp.py  - log_message   
"GET /admin/log/user/ HTTP/1.1" 200 4467 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:45,569 - basehttp.py  - log_message   
"GET /admin/jsi18n/ HTTP/1.1" 200 3185 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:45,642 - basehttp.py  - log_message   
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:46,770 - basehttp.py  - log_message   
"GET /admin/log/user/1/change/ HTTP/1.1" 200 5271 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:46,808 - basehttp.py  - log_message   
"GET /admin/jsi18n/ HTTP/1.1" 200 3185 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 14:43:52,441 - basehttp.py  - log_message   
"GET /admin/log/user/ HTTP/1.1" 200 4346 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 15:13:13,094 - basehttp.py  - log_message   
"GET /polls/ HTTP/1.1" 200 368 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 15:14:30,869 - basehttp.py  - log_message   
"GET /polls/ HTTP/1.1" 200 368 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 15:15:47,901 - basehttp.py  - log_message   
"GET /polls/ HTTP/1.1" 200 368 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 15:21:55,837 - basehttp.py  - log_message   
"GET /polls/ HTTP/1.1" 200 368 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 15:22:05,295 - basehttp.py  - log_message   
"GET /account/log HTTP/1.1" 301 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 15:22:05,301 - basehttp.py  - log_message   
"GET /account/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 15:38:27,818 - basehttp.py  - log_message   
"GET /account/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[WARNING]- 2018-02-22 15:38:35,131 - base.py      - get_response   
Not Found: /auth/login/ 
--------------------------------------------------------------------------------
[WARNING]- 2018-02-22 15:38:35,133 - basehttp.py  - log_message   
"POST /auth/login/ HTTP/1.1" 404 2288 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 15:42:01,094 - basehttp.py  - log_message   
"GET /account/log/ HTTP/1.1" 200 326 
--------------------------------------------------------------------------------
[WARNING]- 2018-02-22 15:42:02,464 - base.py      - get_response   
Not Found: /auth/login/ 
--------------------------------------------------------------------------------
[WARNING]- 2018-02-22 15:42:02,466 - basehttp.py  - log_message   
"POST /auth/login/ HTTP/1.1" 404 2288 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 15:42:21,404 - basehttp.py  - log_message   
"GET /account/log/ HTTP/1.1" 200 329 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 15:43:54,794 - basehttp.py  - log_message   
"POST /account/login/ HTTP/1.1" 200 40 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 15:45:07,540 - basehttp.py  - log_message   
"GET /admin/ HTTP/1.1" 200 6479 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 15:45:07,787 - basehttp.py  - log_message   
"GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 15:45:11,006 - basehttp.py  - log_message   
"GET /admin/log/user/ HTTP/1.1" 200 4346 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 15:45:11,031 - basehttp.py  - log_message   
"GET /admin/jsi18n/ HTTP/1.1" 200 3185 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 15:45:12,889 - basehttp.py  - log_message   
"GET /admin/log/user/1/change/ HTTP/1.1" 200 5271 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 15:45:12,913 - basehttp.py  - log_message   
"GET /admin/jsi18n/ HTTP/1.1" 200 3185 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 15:46:00,919 - basehttp.py  - log_message   
"POST /account/login/ HTTP/1.1" 200 177 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 15:47:09,950 - basehttp.py  - log_message   
"GET /account/log/ HTTP/1.1" 200 329 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 15:47:14,391 - basehttp.py  - log_message   
"POST /account/login/ HTTP/1.1" 200 40 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 15:47:23,004 - basehttp.py  - log_message   
"POST /account/login/ HTTP/1.1" 200 144 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 15:48:58,462 - basehttp.py  - log_message   
"POST /account/login/ HTTP/1.1" 200 40 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 15:49:09,773 - basehttp.py  - log_message   
"GET /account/reg HTTP/1.1" 301 0 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 15:49:09,778 - basehttp.py  - log_message   
"GET /account/reg/ HTTP/1.1" 200 382 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 15:55:32,649 - basehttp.py  - log_message   
"GET /account/reg/ HTTP/1.1" 200 382 
--------------------------------------------------------------------------------
[ERROR ]- 2018-02-22 15:55:34,660 - exception.py - handle_uncaught_exception   
Internal Server Error: /account/register/ 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\github\django_template\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:/github/django_template\project\common\decorator.py", line 19, in _deco
    return func(request, *args, **kwargs)
  File "E:/github/django_template\project\apps\log\views.py", line 48, in register
    user = User.objects.filter(username__exact = request.POST.username)
AttributeError: 'QueryDict' object has no attribute 'username'
[ERROR ]- 2018-02-22 15:55:34,772 - basehttp.py  - log_message   
"POST /account/register/ HTTP/1.1" 500 76107 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 15:57:20,627 - basehttp.py  - log_message   
"GET /account/reg/ HTTP/1.1" 200 382 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 15:57:27,731 - basehttp.py  - log_message   
"POST /account/register/ HTTP/1.1" 200 21 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 15:57:54,420 - basehttp.py  - log_message   
"POST /account/register/ HTTP/1.1" 200 17 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 16:00:10,103 - basehttp.py  - log_message   
"GET /admin/log/user/ HTTP/1.1" 200 4562 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 16:00:11,806 - basehttp.py  - log_message   
"GET /admin/log/user/7/change/ HTTP/1.1" 200 5246 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 16:00:11,837 - basehttp.py  - log_message   
"GET /admin/jsi18n/ HTTP/1.1" 200 3185 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 16:00:18,217 - basehttp.py  - log_message   
"GET /account/log/ HTTP/1.1" 200 329 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 16:00:28,335 - basehttp.py  - log_message   
"POST /account/login/ HTTP/1.1" 200 141 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 16:00:59,199 - basehttp.py  - log_message   
"GET /admin/log/user/ HTTP/1.1" 200 4562 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 16:51:52,697 - basehttp.py  - log_message   
"GET /account/log/ HTTP/1.1" 200 329 
--------------------------------------------------------------------------------
[INFO  ]- 2018-02-22 16:51:56,378 - basehttp.py  - log_message   
"GET /polls/ HTTP/1.1" 200 368 
--------------------------------------------------------------------------------
